/**
 * @file ntripclient_nodelet.h
 * @author 
 * @brief 
 * @version 0.1
 * @date 2022-10-25
 * 
 * @copyright Copyright (c) 2022 Stellantis
 * 
 */
#pragma
#include <stdint.h>
#include <stdio.h>
#include <ros/ros.h>
//Nodelet headers
#include <nodelet/nodelet.h>
#include <pluginlib/class_list_macros.h>

//Receive starts a new thread
#include <thread>

//Autogenerated header files begin here
#include<sys/socket.h>
#include<arpa/inet.h>	//inet_addr



namespace ntripclient
{

class ntripclientNodelet : public nodelet::Nodelet
	{
	public:
		/**
		 * @brief Construct a new ntripclientNodelet::ntripclientNodelet object
		 *
		 */
		//ntripclientNodelet(){}ros::Publisher m_publisherCompressedImage;

	private:
		/**
		 * @brief Nodelet entry point function
		 *
		 */
		
		void onInit();
		

	};

};  // namespace ntripclient